import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  plugins: [tsconfigPaths(), react()],
  test: {
    testTimeout: 15000,
    globals: true,
    setupFiles: ["vitest.setup.ts"],
    environment: "jsdom",
    coverage: {
      provider: "v8",
      reporter: ["text", "lcov", "json-summary"],
      reportsDirectory: "coverage",
      all: true,
      thresholds: {
        statements: 80,
        branches: 80,
        functions: 80,
        lines: 80,
      },
      exclude: [
        "__tests__/*",
        "middleware.ts",
        "**/*.stories.{ts,tsx}",
        "components/ui/**",
        "hooks/use-toast.ts", // hook from shadcn
        "lib/paths.ts", // The helper is static
        // Temp exlucude for WIP components
        "components/CreatePosition/*",
        "**/app/**/[lang]/page.tsx",
        "app/*/*/*/page.tsx",
        "app/*/*/*/details/page.tsx",
        "**/app/**/dashboard/home/page.tsx",
        "**/app/**/dashboard/positions/page.tsx",
        "**/app/**/dashboard/positions/**/page.tsx",
        "components/TopBar/*",
        "components/UserMenu/*",
        "components/UserInfo/*",
        "components/Openings/*",
        "components/OpeningTracking/*",
        "components/Board/*",
        "components/BoardColumn/*",
        "components/Board/UserCard*",
        "components/CancelApplicationDialog/*",
        "components/CandidateDetailsDialog/*",
        "components/CreateUserDialog/*",
        "components/WalkthroughDialog/*",
        "components/UserSettingsTab/*",
        "components/StartFormDialog/*",
        "components/SendApplicationDialog/*",
        "components/CommentBox/*",
        "components/EditableField/*",
        "components/Notifications/*",
        "components/EditUserDialog/*",
        "components/UserCard/*",
        "components/PhaseHistory/*",
        "components/SideBar/SideBar.tsx",
        "components/CompanyDetailsForm/*",
        "components/CountryLabel/*",
        "components/CreateBusinessDialog/*",
        "components/FileDropzone/*",
        "constants/*",
        "icons/*",
        "lib/utils.ts",
        "lib/store/features/notifications/notifications.ts",
        "types/*",
        "lib/pipefy/*",

        // End Temp exlucude for WIP components
        ".storybook",
        ".next",
        "*.d.ts",
        "*.config.{ts,js,mts,mjs}",
        "lib/theme/index.ts",
      ],
    },
  },
});
