name: Code quality, tests and build

on:
  pull_request:
    branches: [main, develop]

jobs:
  ci_test_and_quality_checks:
    name: CI test and quality checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js 18.8
        uses: actions/setup-node@v2
        with:
          node-version: 18.8
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Run test coverage
        run: npm run test:coverage

      - name: Build the app
        run: npm run build
